version: '3'
services:
   catalog-module:
     image: darshansbg/catalog-service:latest
     ports:
     - "8000:8000"
   redis:
     image: redis:alpine
   Review-Module:
     image: darshansbg/review-service
     ports:
     - "9000:9000"
  Order-Module:
     image: darshansbg/order-service
     ports:
     - "9500:9500"
